const START_LOADING = 'START_LOADING';
const STOP_LOADING = 'STOP_LOADING';
const SET_USER = 'SET_USER';
const REMOVE_USER = 'REMOVE_USER';

export { START_LOADING, STOP_LOADING, SET_USER, REMOVE_USER };
